import Image from "next/image";
import Link from "next/link";
import { heritages } from "@/lib/heritage";

export default function GalleryPage() {
  return <main>
    <header className="shell nav"><Link className="brand" href="/">SMART ART HERITAGE · V1.0</Link><Link className="button ghost" href="/ban-do">Kho di sản</Link></header>
    <section className="page-head"><div className="shell"><div className="breadcrumbs">Trang chủ / Gallery</div><div className="kicker">Không gian trưng bày V1</div><h1>Gallery sáng tạo<br/>từ di sản.</h1><p className="lead">Không gian này giới thiệu hành trình sáng tạo và dẫn người xem quay về nguồn học liệu. Tác phẩm học sinh chỉ được công khai sau khi có sự đồng ý phù hợp.</p></div></section>
    <section className="content"><div className="shell"><div className="notice"><strong>Gallery mẫu — chưa hiển thị dữ liệu học sinh thật.</strong><br/>Bản V1 dùng để trưng bày cấu trúc và hướng dẫn QR. Khi triển khai chính thức, giáo viên chỉ thêm những tác phẩm đã được phép công bố.</div><div className="gallery-grid">{heritages.map((heritage) => <article className="gallery-card" key={heritage.slug}><div className="gallery-art"><span>{heritage.code}</span></div><div className="heritage-code">CẢM HỨNG TỪ {heritage.name.toUpperCase()}</div><h2>{heritage.artisticFocus}</h2><p className="small">Khám phá học liệu, hoàn thành 3–2–1 và ghi ý tưởng vào Portfolio trước khi đưa tác phẩm vào Gallery.</p><div className="gallery-actions"><Link className="link" href={`/di-san/${heritage.slug}`}>Mở hồ sơ di sản →</Link><Link className="link" href={`/portfolio?heritage=${heritage.slug}`}>Ghi Portfolio →</Link></div></article>)}</div><section className="qr-panel" aria-labelledby="qr-title"><div><div className="kicker">QR triển lãm</div><h2 id="qr-title">Quét để vào Gallery</h2><p className="small">Đặt mã này tại lớp học hoặc triển lãm. Mã dẫn trực tiếp đến Gallery công khai, hoạt động trên điện thoại và không dùng địa chỉ localhost.</p><p className="qr-url">smart-art-heritage.vercel.app/gallery</p><Link className="button ghost" href="/huong-dan">Xem hướng dẫn triển khai →</Link></div><figure><Image src="/qr/smart-art-gallery.png" alt="Mã QR dẫn đến Gallery SMART ART HERITAGE" width={1200} height={1200} priority/><figcaption>SMART ART HERITAGE · Gallery V1</figcaption></figure></section></div></section>
  </main>;
}
