import Link from "next/link";
import { heritages } from "@/lib/heritage";

export default function GalleryPage() {
  return <main>
    <header className="shell nav"><Link className="brand" href="/">SMART ART HERITAGE · V1.0</Link><Link className="button ghost" href="/ban-do">Kho di sản</Link></header>
    <section className="page-head"><div className="shell"><div className="breadcrumbs">Trang chủ / Gallery</div><div className="kicker">Không gian trưng bày V1</div><h1>Gallery sáng tạo<br/>từ di sản.</h1><p className="lead">Không gian này giới thiệu hành trình sáng tạo và dẫn người xem quay về nguồn học liệu. Tác phẩm học sinh chỉ được công khai sau khi có sự đồng ý phù hợp.</p></div></section>
    <section className="content"><div className="shell"><div className="notice"><strong>Gallery mẫu — chưa hiển thị dữ liệu học sinh thật.</strong><br/>Bản V1 dùng để trưng bày cấu trúc và hướng dẫn QR. Khi triển khai chính thức, giáo viên chỉ thêm những tác phẩm đã được phép công bố.</div><div className="gallery-grid">{heritages.map((heritage) => <article className="gallery-card" key={heritage.slug}><div className="gallery-art"><span>{heritage.code}</span></div><div className="heritage-code">CẢM HỨNG TỪ {heritage.name.toUpperCase()}</div><h2>{heritage.artisticFocus}</h2><p className="small">Khám phá học liệu, hoàn thành 3–2–1 và ghi ý tưởng vào Portfolio trước khi đưa tác phẩm vào Gallery.</p><div className="gallery-actions"><Link className="link" href={`/di-san/${heritage.slug}`}>Mở hồ sơ di sản →</Link><Link className="link" href={`/portfolio?heritage=${heritage.slug}`}>Ghi Portfolio →</Link></div></article>)}</div><div className="panel" style={{marginTop:26}}><div className="kicker">QR triển lãm</div><h2>Chuẩn bị để đặt tại lớp học hoặc triển lãm</h2><p className="small">Sau khi website được triển khai với tên miền công khai, một QR sẽ dẫn trực tiếp đến trang Gallery này. QR không sử dụng địa chỉ localhost để bảo đảm mở được trên điện thoại của khách tham quan.</p></div></div></section>
  </main>;
}
