export type ReflectionPack = {
  title: string;
  prompts: [string, string, string];
  hints: [string, string, string];
};

export const reflectionBank: Record<string, ReflectionPack[]> = {
  "pho-hien": [
    { title: "Dấu ấn Phố Hiến", prompts: ["Ghi 3 hình ảnh/chi tiết khiến em nhận ra nét riêng của Phố Hiến.", "Chọn 2 chi tiết có thể kể chuyện về Phố Hiến; nói vì sao em chọn.", "Nếu tạo 1 sản phẩm Mĩ thuật về Phố Hiến, em sẽ làm gì và muốn người xem nhớ điều gì?"], hints: ["Quan sát lại ảnh và ghi đúng các chi tiết em thực sự nhìn thấy: đường nét, hình khối, màu sắc, không gian hoặc hoa văn.", "Giải thích lựa chọn bằng đặc điểm tạo hình, cảm xúc hoặc ý nghĩa em nhận ra; tránh chỉ viết ‘đẹp’.", "Có thể là tranh, poster, bưu thiếp, mô hình hoặc thiết kế số; hãy nêu dấu ấn riêng của em."] },
    { title: "Kiến trúc & không gian", prompts: ["Tìm 3 đặc điểm về đường nét, hình khối hoặc không gian trong ảnh Phố Hiến.", "Chọn 2 đặc điểm tạo hình em muốn giữ lại khi sáng tạo và giải thích.", "Đề xuất 1 bố cục mới lấy cảm hứng Phố Hiến nhưng không sao chép nguyên ảnh."], hints: ["Quan sát mái, cổng, lối đi, mảng sáng tối và các lớp không gian.", "Nêu rõ đặc điểm nào khiến em muốn giữ lại trong tác phẩm.", "Biến đổi góc nhìn, tỉ lệ hoặc cách sắp xếp để tác phẩm là của riêng em."] },
    { title: "Màu sắc & cảm xúc", prompts: ["Ghi 3 màu/nhóm màu nổi bật và cảm giác chúng đem lại.", "Chọn 2 màu làm chủ đạo; chúng giúp em thể hiện cảm xúc gì về Phố Hiến?", "Tạo 1 ý tưởng sản phẩm dùng bảng màu riêng để thể hiện Phố Hiến theo cảm nhận cá nhân."], hints: ["Nhìn cả màu vật liệu, cây cối, bầu trời và vùng sáng tối.", "Liên hệ màu với cảm giác như cổ kính, ấm áp, yên bình hoặc nhộn nhịp.", "Em có thể thay đổi sắc độ để tạo bảng màu mang cá tính riêng."] },
    { title: "Xưa & nay", prompts: ["Nêu 3 dấu hiệu giúp em liên hệ Phố Hiến xưa với Phố Hiến hôm nay.", "Chọn 2 yếu tố: một gợi quá khứ, một gợi hiện tại; em sẽ kết hợp thế nào?", "Nghĩ 1 sản phẩm Mĩ thuật kể cuộc gặp giữa Phố Hiến xưa và nay."], hints: ["Tìm dấu vết kiến trúc, nhịp sống, vật liệu hoặc câu chuyện giao thương.", "Hãy chỉ rõ yếu tố nào là xưa và yếu tố nào là nay.", "Dùng tương phản, lớp thời gian hoặc hai mảng hình để kể chuyện."] },
    { title: "Biểu tượng cá nhân", prompts: ["Chọn 3 chi tiết Phố Hiến có thể biến thành hình ảnh biểu tượng.", "So sánh 2 chi tiết em thích: chi tiết nào dễ cách điệu, chi tiết nào kể chuyện tốt hơn?", "Từ 1 chi tiết, hãy nêu cách biến đổi thành logo, họa tiết, biểu tượng hoặc sản phẩm ứng dụng."], hints: ["Ưu tiên chi tiết có hình dáng rõ và dễ nhận ra.", "So sánh đường nét, hình khối và khả năng gợi câu chuyện.", "Thử giản lược, lặp lại hoặc thay đổi tỉ lệ chi tiết em chọn."] },
  ],
  "chua-keo": [
    { title: "Nhịp điệu mái chùa", prompts: ["Ghi 3 đặc điểm ở hệ mái, đường cong hoặc nhịp lặp kiến trúc Chùa Keo.", "Chọn 2 đặc điểm tạo nhịp điệu thị giác rõ nhất và nêu cảm giác chúng tạo ra.", "Từ nhịp điệu mái Chùa Keo, đề xuất 1 sản phẩm Mĩ thuật có bố cục riêng."], hints: ["Quan sát đường cong, lớp mái, cột và khoảng lặp.", "Nói rõ nhịp điệu tạo cảm giác yên tĩnh, vững chãi hay chuyển động.", "Không cần vẽ lại ngôi chùa; hãy dùng nhịp điệu làm chất liệu sáng tạo."] },
    { title: "Hình khối kiến trúc", prompts: ["Tìm 3 hình khối/dạng hình cơ bản trong kiến trúc Chùa Keo.", "Chọn 2 hình khối đặc trưng và giải thích chúng liên kết với nhau ra sao.", "Dùng các hình khối đã chọn để nghĩ 1 bố cục mới, không vẽ lại nguyên công trình."], hints: ["Tìm hình tam giác, chữ nhật, khối mái hoặc khoảng trống.", "Quan sát sự cân bằng, chồng lớp và tỉ lệ giữa các hình.", "Có thể cắt, ghép hoặc sắp xếp lại thành bố cục mới."] },
    { title: "Hoa văn & chi tiết gỗ", prompts: ["Ghi 3 đường nét, hoa văn hoặc chi tiết chạm khắc em chú ý.", "Chọn 2 chi tiết muốn cách điệu; em sẽ giữ gì và thay đổi gì?", "Tạo 1 ý tưởng họa tiết hoặc sản phẩm trang trí mới từ chi tiết Chùa Keo."], hints: ["Quan sát nét cong, nét thẳng, phần lặp lại và bề mặt gỗ.", "Giữ nét đặc trưng nhưng thay đổi tỉ lệ, màu hoặc nhịp lặp.", "Thử đưa họa tiết vào bìa sổ, khăn, thiệp hoặc poster."] },
    { title: "Không gian & góc nhìn", prompts: ["Nêu 3 lớp không gian em nhận ra khi nhìn Chùa Keo từ ngoài vào trong.", "Chọn 2 góc nhìn thú vị nhất để giới thiệu Chùa Keo và giải thích.", "Chọn 1 góc nhìn cho tác phẩm; em sẽ tạo điểm nhấn và bố cục riêng thế nào?"], hints: ["Nhìn tiền cảnh, trung cảnh, hậu cảnh; cổng, sân, mái và cây.", "Góc nhìn cần giúp người xem thấy điều em muốn kể.", "Quyết định hình chính, hình phụ và vùng nhấn sáng tối."] },
    { title: "Chùa Keo hiện đại", prompts: ["Chọn 3 yếu tố Chùa Keo có thể đưa vào thiết kế dành cho học sinh hôm nay.", "Chọn 2 yếu tố và nêu cách hiện đại hóa mà vẫn nhận ra nguồn cảm hứng.", "Đề xuất 1 sản phẩm hiện đại mang cảm hứng Chùa Keo và nét riêng của em."], hints: ["Có thể chọn hình mái, nhịp cột, họa tiết hoặc bảng màu.", "Hiện đại hóa bằng màu, vật liệu, công năng hoặc cách trình bày.", "Nêu người dùng, sản phẩm và thông điệp chính."] },
  ],
  "den-tran": [
    { title: "Dấu ấn lịch sử", prompts: ["Ghi 3 hình ảnh/chi tiết làm em cảm nhận rõ không gian lịch sử Đền Trần.", "Chọn 2 chi tiết có khả năng kể chuyện lịch sử bằng hình ảnh; vì sao?", "Nghĩ 1 sản phẩm Mĩ thuật giúp bạn cùng tuổi cảm nhận lịch sử Đền Trần."], hints: ["Quan sát cổng, mái, biểu tượng, không gian thờ tự và cảnh quan.", "Chi tiết tốt có thể gợi một câu chuyện hay một cảm xúc lịch sử.", "Hãy chọn cách kể gần gũi với học sinh cùng tuổi."] },
    { title: "Kiến trúc trang nghiêm", prompts: ["Tìm 3 đặc điểm về hình khối, trục, cân đối hoặc nhịp điệu kiến trúc.", "Chọn 2 đặc điểm tạo cảm giác trang nghiêm; em sẽ thể hiện chúng ra sao?", "Tạo 1 bố cục mới lấy cảm hứng kiến trúc Đền Trần nhưng mang cảm nhận riêng."], hints: ["Tìm trục giữa, sự đối xứng, nhịp cột hoặc lớp mái.", "Dùng tỉ lệ, đường thẳng, màu sắc và khoảng trống để tạo cảm giác.", "Không sao chép toàn cảnh; chọn vài yếu tố làm ngôn ngữ riêng."] },
    { title: "Biểu tượng & hoa văn", prompts: ["Ghi 3 hoa văn, biểu tượng hoặc chi tiết trang trí em muốn tìm hiểu.", "Chọn 2 chi tiết và so sánh đường nét, hình dáng hoặc hiệu quả thị giác.", "Chọn 1 chi tiết để cách điệu thành họa tiết/biểu tượng mới cho sản phẩm."], hints: ["Hãy mô tả hình dáng trước khi suy đoán ý nghĩa.", "So sánh điểm giống, khác và cảm giác mỗi chi tiết tạo ra.", "Giản lược thành các nét chính để tạo biểu tượng mới."] },
    { title: "Không gian tưởng niệm", prompts: ["Nêu 3 yếu tố tạo cảm giác yên tĩnh, trang trọng hoặc tưởng niệm.", "Chọn 2 yếu tố em sẽ dùng để tạo cảm xúc cho người xem.", "Không vẽ toàn bộ Đền Trần: em sẽ dùng 1 hình ảnh nào để gợi tinh thần nơi này?"], hints: ["Lưu ý ánh sáng, khoảng trống, cây xanh, trục đi và màu sắc.", "Chọn yếu tố có thể chuyển thành hình, màu hay bố cục.", "Một hình ảnh được chọn kỹ có thể gợi cả không gian."] },
    { title: "Di sản với thế hệ trẻ", prompts: ["Ghi 3 điều về Đền Trần mà học sinh cùng tuổi nên biết hoặc quan sát.", "Chọn 2 thông điệp em muốn truyền tới bạn bè bằng Mĩ thuật.", "Thiết kế 1 ý tưởng sản phẩm dành cho học sinh để giới thiệu Đền Trần theo cách mới."], hints: ["Viết điều gần gũi, đúng với quan sát và cảm nhận của em.", "Thông điệp ngắn, rõ, có thể chuyển thành hình ảnh.", "Nêu loại sản phẩm, hình chính và người em muốn hướng tới."] },
  ],
  "le-quy-don": [
    { title: "Chân dung nhà bác học", prompts: ["Ghi 3 chi tiết giúp em hình dung về con người/sự nghiệp Lê Quý Đôn.", "Chọn 2 chi tiết có thể biểu đạt tinh thần ham học và tri thức.", "Tạo 1 ý tưởng sản phẩm về Lê Quý Đôn mà không chỉ đơn thuần vẽ chân dung."], hints: ["Nghĩ đến việc học, sách vở, nghiên cứu và tinh thần tìm tòi.", "Chọn chi tiết có thể chuyển thành hình ảnh hoặc biểu tượng.", "Em có thể kể bằng sách, chữ, bản đồ tri thức hoặc không gian học tập."] },
    { title: "Không gian lưu niệm", prompts: ["Nêu 3 đặc điểm tạo hình ở kiến trúc/cảnh quan khu lưu niệm.", "Chọn 2 đặc điểm dùng làm nền cho câu chuyện về Lê Quý Đôn; vì sao?", "Nghĩ 1 tác phẩm kết hợp không gian khu lưu niệm với biểu tượng tri thức."], hints: ["Quan sát kiến trúc, lối đi, cây xanh, bia hoặc không gian mở.", "Nền cần hỗ trợ câu chuyện chứ không lấn át nhân vật/chủ đề.", "Kết hợp một không gian và một biểu tượng tri thức."] },
    { title: "Sách & tri thức", prompts: ["Ghi 3 hình ảnh em liên tưởng tới học tập, đọc và nghiên cứu.", "Chọn 2 hình ảnh và nghĩ cách kết hợp thành một biểu tượng về tri thức.", "Thiết kế 1 bìa sách, poster hoặc sản phẩm khác truyền cảm hứng học tập."], hints: ["Hãy nghĩ đến sách, bút, trang giấy, ánh sáng, bản đồ ý tưởng.", "Thử ghép hai hình thành một hình mới có ý nghĩa.", "Xác định tiêu đề, hình chính và thông điệp ngắn."] },
    { title: "Kể chuyện bằng hình ảnh", prompts: ["Chọn 3 mốc/chi tiết/hình ảnh để kể câu chuyện ngắn về Lê Quý Đôn.", "Chọn 2 cách kể bằng Mĩ thuật phù hợp nhất và nêu ưu điểm.", "Chọn 1 cách kể, xác định hình chính, hình phụ và thông điệp của sản phẩm."], hints: ["Sắp xếp chi tiết theo trình tự để người xem dễ theo dõi.", "Có thể dùng tranh truyện, poster, tranh nhiều mảng hoặc biểu tượng.", "Ghi rõ điều người xem cần nhận ra đầu tiên."] },
    { title: "Tri thức hôm nay", prompts: ["Ghi 3 giá trị từ dự án Lê Quý Đôn có thể liên hệ với học sinh hôm nay.", "Chọn 2 giá trị và nghĩ hình ảnh hiện đại có thể biểu đạt chúng.", "Tạo 1 ý tưởng nối tinh thần học tập của Lê Quý Đôn với cuộc sống học sinh hiện nay."], hints: ["Ví dụ: ham học, tò mò, kiên trì, chia sẻ tri thức.", "Chuyển giá trị thành hình ảnh gần gũi với đời sống học sinh.", "Nêu rõ sự nối tiếp giữa quá khứ và hiện tại."] },
  ],
  "dong-xam": [
    { title: "Hoa văn chạm bạc", prompts: ["Ghi 3 đặc điểm đường nét/hoa văn trên sản phẩm chạm bạc Đồng Xâm.", "Chọn 2 họa tiết và nêu điều làm chúng nổi bật trên bề mặt kim loại.", "Chọn 1 họa tiết để phát triển thành mẫu trang trí mới mang dấu ấn cá nhân."], hints: ["Quan sát nét uốn, nét khắc, mảng nổi/chìm và nhịp lặp.", "Hãy nói về đường nét, độ dày, vị trí và ánh sáng.", "Giữ một nét đặc trưng rồi biến đổi thành phong cách riêng."] },
    { title: "Ánh sáng & bề mặt", prompts: ["Nêu 3 thay đổi khi ánh sáng chiếu lên phần nổi–chìm của sản phẩm.", "Chọn 2 hiệu ứng ánh sáng muốn đưa vào tác phẩm hai chiều; làm bằng cách nào?", "Nghĩ 1 sản phẩm không làm bằng bạc nhưng vẫn gợi vẻ óng ánh/nổi–chìm Đồng Xâm."], hints: ["Nhìn vùng sáng, vùng tối, phản chiếu và bóng đổ.", "Có thể dùng bút, màu, giấy kim tuyến, dập nổi hoặc tương phản.", "Chọn vật liệu quen thuộc nhưng giải thích cách tạo hiệu ứng."] },
    { title: "Nhịp điệu trang trí", prompts: ["Tìm 3 kiểu sắp xếp họa tiết trên sản phẩm Đồng Xâm.", "Chọn 2 kiểu sắp xếp và so sánh cảm giác thị giác chúng tạo ra.", "Chọn 1 kiểu nhịp điệu để thiết kế trang trí cho đồ vật quen thuộc với học sinh."], hints: ["Tìm họa tiết lặp, đối xứng, xen kẽ hoặc lan tỏa.", "So sánh cảm giác đều đặn, sôi động, cân bằng hay chuyển động.", "Thử áp dụng cho hộp bút, bìa sổ, túi hoặc huy hiệu."] },
    { title: "Truyền thống → hiện đại", prompts: ["Ghi 3 yếu tố nghề Đồng Xâm nên giữ khi đưa vào sản phẩm hiện đại.", "Chọn 2 yếu tố; em sẽ giữ phần nào và đổi mới phần nào?", "Đề xuất 1 sản phẩm hiện đại lấy cảm hứng Đồng Xâm dành cho người trẻ."], hints: ["Có thể là kỹ thuật, hoa văn, chất liệu, câu chuyện làng nghề.", "Nêu rõ phần giữ lại và phần thay đổi để phù hợp hôm nay.", "Xác định công năng và người dùng của sản phẩm."] },
    { title: "Bảo tồn bằng Mĩ thuật", prompts: ["Nêu 3 điều em muốn giới thiệu để người khác hiểu hơn về chạm bạc Đồng Xâm.", "Chọn 2 cách dùng hình ảnh để giới thiệu nghề hấp dẫn học sinh cùng tuổi.", "Xây dựng 1 ý tưởng sản phẩm Mĩ thuật giúp giới thiệu/gìn giữ nghề Đồng Xâm."], hints: ["Chọn điều cụ thể về người thợ, hoa văn, kỹ thuật hoặc sản phẩm.", "Nghĩ về poster, truyện tranh, video ngắn, logo hoặc bộ nhận diện.", "Nêu thông điệp bảo tồn và trải nghiệm người xem nhận được."] },
  ],
};
