'use client'

import Link from 'next/link'
import { useEffect, useState } from 'react'
import { heritages } from '@/lib/heritage'

const empty = { author: '', title: '', heritage: 'pho-hien', description: '', link: '' }

export default function PortfolioPage() {
  const [form, setForm] = useState(empty)
  const [works, setWorks] = useState([])
  const [saved, setSaved] = useState(false)
  useEffect(() => { try { setWorks(JSON.parse(window.localStorage.getItem('smart-art-portfolio') || '[]')); const query = new URLSearchParams(window.location.search); const passport = JSON.parse(window.localStorage.getItem('smart-art-creative-passport') || 'null'); if (query.get('passport') === '1' && passport) { setForm((current) => ({ ...current, heritage: passport.heritage || current.heritage, title: passport.title || '', description: [passport.message, passport.signature, passport.decision].filter(Boolean).join(' · '), author: passport.author || '' })); } } catch {} }, [])
  const change = (key, value) => setForm((old) => ({ ...old, [key]: value }))
  const submit = (event) => { event.preventDefault(); if (!form.author.trim() || !form.title.trim() || !form.description.trim()) return; const item = { ...form, id: crypto.randomUUID() }; const next = [item, ...works]; setWorks(next); window.localStorage.setItem('smart-art-portfolio', JSON.stringify(next)); setForm(empty); setSaved(true); }
  const remove = (id) => { const next = works.filter((item) => item.id !== id); setWorks(next); window.localStorage.setItem('smart-art-portfolio', JSON.stringify(next)); }
  return <main><header className="shell nav"><Link className="brand" href="/">SMART ART HERITAGE · V1.0</Link><Link className="button ghost" href="/ban-do">Kho di sản</Link></header>
    <section className="page-head"><div className="shell"><div className="breadcrumbs">Kho di sản / Portfolio</div><div className="kicker">Xưởng sáng tạo</div><h1>Lưu ý tưởng.<br/>Ghi dấu tác giả.</h1><p className="lead">Lưu ý tưởng, phác thảo và tác phẩm. Khi đi từ AI 5A, Hộ chiếu sáng tạo sẽ đưa các quyết định của em sang đây để tiếp tục hoàn thiện.</p></div></section>
    <section className="content"><div className="shell two-col"><div><div className="panel"><div className="kicker">Thêm tác phẩm</div><h2>Nhật ký sáng tạo</h2><form onSubmit={submit}><div className="form-field"><label>Tên hoặc mã học sinh</label><input value={form.author} onChange={(e) => change('author', e.target.value)} placeholder="Ví dụ: HS-08 hoặc Minh Anh" /></div><div className="form-field"><label>Tên tác phẩm</label><input value={form.title} onChange={(e) => change('title', e.target.value)} placeholder="Ví dụ: Nhịp mái Chùa Keo" /></div><div className="form-field"><label>Di sản nguồn cảm hứng</label><select value={form.heritage} onChange={(e) => change('heritage', e.target.value)}>{heritages.map((item) => <option value={item.slug} key={item.slug}>{item.name}</option>)}</select></div><div className="form-field"><label>Thuyết minh ngắn: em đã quan sát gì và biến đổi điều gì?</label><textarea value={form.description} onChange={(e) => change('description', e.target.value)} placeholder="Viết 2–4 câu bằng lời của em..." /></div><div className="form-field"><label>Liên kết bài nộp (không bắt buộc)</label><input value={form.link} onChange={(e) => change('link', e.target.value)} placeholder="Google Drive, Padlet hoặc nơi giáo viên yêu cầu" /></div><button className="button" type="submit">Lưu vào Portfolio trên thiết bị này</button>{saved && <p className="small">Đã lưu. Em có thể thêm tác phẩm hoặc xem lại ở phần bên dưới.</p>}</form></div>
      <div className="panel" style={{ marginTop: 20 }}><div className="kicker">Gallery cá nhân</div><h2>Tác phẩm đã ghi nhận</h2>{works.length === 0 ? <p className="small">Chưa có tác phẩm nào trên thiết bị này. Hãy hoàn thành Trợ lý 5A rồi quay lại ghi nhật ký sáng tạo.</p> : <div className="work-list">{works.map((work) => { const heritage = heritages.find((item) => item.slug === work.heritage); return <article className="work-card" key={work.id}><div className="heritage-code">{heritage?.name} · {work.author}</div><h3>{work.title}</h3><p>{work.description}</p>{work.link && <a className="link" href={work.link} target="_blank" rel="noreferrer">Mở bài nộp ↗</a>}<button type="button" className="text-button" onClick={() => remove(work.id)}>Xóa khỏi thiết bị này</button></article> })}</div>}</div></div>
      <aside><div className="panel"><div className="kicker">Cách nộp bài</div><h2>Chỉ lưu trên thiết bị</h2><p className="small">Bản V1 không yêu cầu học sinh tạo tài khoản. Dữ liệu Portfolio được lưu cục bộ trên thiết bị; giáo viên có thể yêu cầu học sinh gửi liên kết tác phẩm qua Google Drive, Padlet hoặc kênh lớp.</p><div className="hotspot"><b>Để trưng bày bằng QR</b>QR Gallery sẽ dẫn tới trang Portfolio/Gallery sau khi website được triển khai với tên miền công khai. Không công khai tác phẩm học sinh khi chưa có sự đồng ý phù hợp.</div><Link className="link" href="/ai-assistant">Quay lại Trợ lý 5A →</Link></div></aside>
    </div></section></main>
}
